### ISSUE TITLE
Breaking with a lot of images

### ISSUE THREAD

**Issue by mbwe** [devongovett/jpg-stream#3]
I get the following message when i want to extract Exif data from around 400 jpeg files. I never seen this message, and have no clue, how to solve this.

Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 33554432, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 33554432, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.

/var/development/node_modules/jpg-stream/build/jpeg.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function";var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!ret&&filename!=nodePath["resolve"](filename)){
abort() at Error
    at jsStackTrace (/var/development/node_modules/jpg-stream/build/jpeg.js:1:18435)
    at stackTrace (/var/development/node_modules/jpg-stream/build/jpeg.js:1:18618)
    at abort (/var/development/node_modules/jpg-stream/build/jpeg.js:42:35740)
    at enlargeMemory (/var/development/node_modules/jpg-stream/build/jpeg.js:1:18951)
    at Function.Runtime.dynamicAlloc [as alloc](/var/development/node_modules/jpg-stream/build/jpeg.js:1:7668)
    at _sbrk (/var/development/node_modules/jpg-stream/build/jpeg.js:1:122885)
    at Ts (/var/development/node_modules/jpg-stream/build/jpeg.js:9:12346)
    at Mi (/var/development/node_modules/jpg-stream/build/jpeg.js:29:62714)
    at Array.Ni (/var/development/node_modules/jpg-stream/build/jpeg.js:29:63216)
    at ng (/var/development/node_modules/jpg-stream/build/jpeg.js:17:61717)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by devongovett** [comment]
Just released a new version which raises the memory limit.
